### ISSUE TITLE
whats difference vs slack official node client?

### ISSUE THREAD

**Issue by dcsan** [krishamoud/meteor-slack-api#1]
kris - thanks for creating this. can you help me understand what's the difference/benefit compared to using slackHQ main node client?
https://github.com/slackhq/node-slack-client

is their client out of date?
does it support the realtime api fully?

just wondering!

**Comment by dcsan** [comment]
well, one problem i got with the official npm package was

> npm is not compatible with architecture 'os.linux.x86_64'

which looks fairly a gnarly thing to work through. 
https://github.com/meteorhacks/npm/issues/40

**Comment by dcsan** [comment]
there's also `slack-node` npm module, another version of similar thing
https://www.npmjs.com/package/slack-node

this is more confusing than meteor packages!

**Comment by krishamoud** [comment]
Hi!  Thanks for writing.  This package was written in meteor which is the only real difference.  We needed this so we didn't have to import a node module.  It was easier than figuring out the node packaging.  If you find a bug please let me know and I will fix it ASAP.

**Comment by dcsan** [comment]
just out of interest, what problems did you have when importing the node packaging? `Meteor.npmRequire()` superficially makes that pretty easy, so what did you anticipate as problems?
stuff to do with deployment? 
I had the problem above, re build for specific OS environments.

I assume your package won't have this issue as you're using any native code in your package?

I also had some problems with not being able to call external APIs from within the node callbacks, issues around Fibers and BindEnvironment. but those may not be specific to the node package, maybe more a meteor issue.

**Comment by krishamoud** [comment]
Closing.  This package will probably not be very needed with Meteor 1.3 being more npm accessible.
