### ISSUE TITLE
message with attachments

### ISSUE THREAD

**Issue by dcsan** [krishamoud/meteor-slack-api#3]
I was trying to use the chat.postMessage method you have and your API is slightly different than slacks

wondering if you only support text messages? I tried adding an attachment inside `options` but doesn't seem to render.

https://api.slack.com/methods/chat.postMessage

**Comment by krishamoud** [comment]
Good catch.  I'll see if I can fix that today.

**Comment by dcsan** [comment]
note that the way attachments are handled, they need to be `JSON.stringify`'d
https://github.com/slackhq/node-slack-client/issues/12

this took some time to figure out a way back!

**Comment by Ethaan** [comment]
+1 i need this one, i may be doing a PR of this

**Comment by xavxyz** [comment]
Well I've had the same problem for a while now, and decided to fix it : #5 
Btw, I added the support for `icon_emoji` in the options.
What do you think @krishamoud, can you merge it?

**Comment by krishamoud** [comment]
Closed with https://github.com/krishamoud/meteor-slack-api/pull/5
